### ISSUE TITLE
FR: Option to choose between time of track or percentage of track

### ISSUE THREAD

**Issue by redactedscribe** [grimes2/foo_preview#1]
It would be cool if the component was configurable and we could choose between using the previous track's time as the playback position for the next track (currently how it works), or the previous track's playback position in percent.

The issue with how it currently works is that we can listen to one track which is 10:00 minutes long, choose the playback position of 4:00 minutes, then after 10(?) seconds the next track plays and it may only be 5:00 minutes long (thus we're only hearing the ending minute of that track). If the next track was 1:00 instead, we would hear only the last 10 seconds.

If basing the position to use on a percentage position of the last track, the preview could be used to preview the 50% middle of the track each time, for example.

Thanks for foo_preview.

**Comment by grimes2** [comment]
Please configure foo_preview in the Advanced Preferences of foobar2000.

**Comment by redactedscribe** [comment]
Thank you! I did not think to look for what I consider to be fundamental options in the advanced section of the preferences. For anyone interested, the option to enabled is "Preview start in %".
